'use strict';

// Kept alongside the experience slice; uses the same dictionary and locale as the app.
if (typeof I18n !== 'undefined' && I18n.dict) {
    Object.assign(I18n.dict.ar, {
        inspect_card: 'افحص البطاقة', inspect_close: 'ارجع ليدك', inspect_now: 'أثرها الآن',
        insight_discard_choice: 'ستتخلّص من هذه البطاقة الإضافية دون تشغيل قوتها أو تغيير اللون.',
        insight_give_choice: 'ستعطي هذه البطاقة إلى {name} دون تشغيل قوتها.',
        inspect_wait: 'تقدر تفحصها الآن؛ اللعب عندما يأتي دورك.',
        inspect_mismatch: 'غير متاحة الآن: طابق {color} أو الشخصية في المرمى.',
        inspect_penalty: 'عليك سحب {n}. هذه البطاقة لا ترد على العقوبة.',
        inspect_legal: 'متاحة للعب الآن.', inspect_resolving: 'أكمل القرار الحالي أولًا.',
        insight_normal: 'تخلّص من هذه البطاقة. لا أثر إضافي لها.',
        insight_skip: 'يتخطى الدور {name}.',
        insight_reverse: 'ينعكس الاتجاه؛ الدور التالي لـ {previous}.',
        insight_draw2: 'تصبح العقوبة {n} على {name}؛ يستطيع الرد إن امتلك بطاقة مناسبة.',
        insight_counterAttack: 'ينعكس الاتجاه وتصبح العقوبة {n} على {previous}؛ له فرصة الرد.',
        insight_draw4Wild: 'اختر اللون. تصبح العقوبة {n} على {name}، مع فرصة الرد.',
        insight_meh: 'اختر اللون. تصبح العقوبة {n} على {name}، مع فرصة الرد.',
        insight_wild: 'اختر اللون الذي سيستمر عليه اللعب.',
        insight_sorry: 'تسحب أنت بطاقتين، ثم ينتقل الدور.',
        insight_sorry_shield: 'درع الفانتوم الحالي يلغي سحبك للبطاقتين ويُستهلك، ثم ينتقل الدور.',
        insight_plato: 'تخلّص من البطاقة، لكن دورك القادم سيُتخطى.',
        insight_chameleon: 'اختر خصمًا وأعطه بطاقة إضافية من يدك، دون تشغيل قوتها.',
        insight_nokhtha: 'تلعب مرة أخرى مباشرة بعد هذه البطاقة.',
        insight_hamour: 'استرجع آخر أربع بطاقات تحت الهامور من المرمى إلى يدك.',
        insight_bestOne: 'تختار: {name} يتخلّص من بطاقتين أو يسحب بطاقتين.',
        insight_dramaQueen: 'يتخطى الدور {name} و{second}.',
        insight_sugar: 'تتوقف القوى الخارقة حتى يعود الدور إليك. السحب والردود تبقى وفق قواعدها.',
        insight_umWajhain: 'اختر خصمًا، ثم قرر: يتخلّص من بطاقة أو يسحب بطاقة.',
        insight_boShlakh: 'اختر بطاقة إضافية تتخلّص منها؛ لا تنفذ قوتها ولا تغيّر اللون.',
        insight_phantom: 'ألغِ العقوبة المعلقة، واحصل على درع يلغي أول سحب لاحق عليك.',
        insight_suppressed: 'قوتها معطلة بشوقر الآن؛ ستتخلص من البطاقة دون تنفيذ القوة.',
        insight_hamour_count: 'سيضاف إلى يدك {n} من المرمى.',
        insight_public_stack: 'يعتمد العدد على البطاقات المتبقية تحتها في المرمى (حتى 4).',
        insight_self_cost: 'تنبيه: العقوبة عليك، وليست على الخصم.',
        insight_skip_cost: 'ثمنها: تفوّت فرصة لعب في دورتك القادمة.',
        art_loading: 'تحميل البطاقة…', art_retry: 'أعد تحميل الصورة', art_unavailable: 'تعذّر تحميل الآرت الأصلي',
        state_sugar: 'القوى معطلة حتى دور {name}', state_shield: 'درع سحب', state_last: 'بطاقة أخيرة',
        decision_card_discard: 'اختر بطاقة تتخلّص منها — {card}',
        decision_card_give: 'اختر بطاقة تعطيها — {card}',
        decision_target: 'اختر من يتأثر — {card}', decision_color: 'اختر اللون — {card}',
        decision_wait: '{name} يختار الآن', decision_count: '{name} · {n} بطاقات',
        decision_finish_warning: 'تنبيه: هذا الاختيار قد ينهي يد {name} ويفوّزه.',
        journal_penalty: '{name} سحب {n} بسبب العقوبة',
        journal_draw_count: '{name} سحب {n} بطاقات',
        journal_powers_restored: 'عادت القوى مع دور {name}',
        journal_decision: '{name} اختار: {choice}',
        journal_skipped: 'تُخطّي دور {name}', journal_effect: '{card}: {effect}',
        first_choice_tip: 'هذا القرار لك؛ اختر بعد قراءة أثر كل خيار.',
        decision_expired: 'انتهى وقت القرار وتغير الدور. راجع حالة الطاولة الآن.',
        bot_style_racer: 'سبّاق', bot_style_guardian: 'حذر', bot_style_tactician: 'مناوش',
        solo_menu: 'إيقاف', solo_paused: 'اللعبة متوقفة', solo_continue: 'نكمّل',
        solo_saved_description: 'تُحفظ الجولة تلقائيًا على هذا الجهاز. يمكنك الرجوع وإكمال القرار.',
        solo_save_failed: 'الحفظ غير متاح لهذه الجولة. لا تغلق الصفحة إذا أردت إكمالها.',
        solo_save_invalid: 'لا توجد جولة محفوظة صالحة لهذه النسخة والعضو. تقدر تبدأ جولة جديدة.',
        solo_resume: 'أكمل جولتك المحفوظة', solo_resume_title: 'جولتك السابقة ما زالت هنا',
        solo_resume_description: 'يمكنك إكمالها أو استبدالها بجولة جديدة. الاستبدال يترك الجولة غير المكتملة دون نتيجة.',
        solo_save_exit: 'حفظ وخروج', solo_exit: 'اخرج', solo_stay: 'أبقى في الجولة',
        solo_exit_title: 'تطلع من الجولة؟', solo_replace: 'اترك المحفوظة وابدأ جولة جديدة',
        solo_finish_fact: 'انتهت يد {name} أولًا.', solo_wins: '{n} انتصارات', solo_rounds: '{n} جولات في هذه الجلسة',
        solo_discard_moment: '{name} تخلّص من {card} باستخدام {source} دون تشغيل قوتها.',
        practice_entry: 'تعلّمها في 3 مواقف',
        practice_position: 'تدريب {n}/3', practice_retry: 'إعادة الموقف', practice_next: 'الموقف التالي',
        practice_skip: 'تجاوز إلى مباراة كاملة', practice_full_game: 'ابدأ مباراة كاملة',
        practice_goal_1: 'افحص بطاقاتك. العب بطاقة تطابق لون المرمى أو شخصيته؛ الفحص لا يلعب البطاقة.',
        practice_goal_2: 'عليك +2. افحص الهجوم المضاد: يعكس الاتجاه ويردّ العقوبة مع بطاقتين إضافيتين.',
        practice_goal_3: 'بوشلاخ يسمح برمي بطاقة إضافية دون تفعيلها. جرّبه للتخلص من «أنا آسف» وثمن سحبها.',
        practice_success_1: 'طابقت البطاقة ورميتها بعد فحصها. في المباراة الكاملة تستطيع فحص أي بطاقة حتى خارج دورك.',
        practice_success_2: 'انعكس الاتجاه ووصلت العقوبة +4 إلى المهاجم؛ سحب أربع بطاقات فعلًا. لو امتلك ردًا لاستطاع الرد.',
        practice_success_3: 'تخلّصت من بوشلاخ و«أنا آسف» وبقيت بطاقة واحدة، دون سحب بطاقتين. هذه توليفة من القواعد الأصلية.',
        practice_alternative: 'نُفّذ اختيارك بقواعد اللعبة. راجع المرمى وعدد البطاقات؛ أعد الموقف لتجربة التوليفة المقترحة، أو أكمل.',
        practice_counter_cause: 'المهاجم لعب «اسكت اسكت»: عقوبة بطاقتين.',
        telemetry_label: 'تسجيل تجربة اللعب محليًا (اختياري)',
        telemetry_description: 'يسجّل الأفعال وأنواع القرارات وفترات انتظار التحكم بمعرّف عشوائي، دون اسمك أو محتوى الأيدي. يبقى على جهازك ولا يُرسل تلقائيًا. إيقافه يمسح السجل؛ يمكنك تصديره ومشاركته بنفسك.',
        telemetry_export: 'تنزيل سجل التجربة JSON', telemetry_empty: 'فعّل التسجيل وجرّب اللعب أولًا.',
        practice_entry_description: 'جرّب المطابقة والرد والتوليفة بنفس القواعد، دون احتساب نتائج.',
        practice_no_rewards: 'موقف تدريبي بأيدٍ مرتبة للتعلّم؛ نفس القواعد، دون نتائج أو تاماشي.',
    });
    Object.assign(I18n.dict.en, {
        inspect_card: 'Inspect card', inspect_close: 'Back to hand', inspect_now: 'What happens now',
        insight_discard_choice: 'Shed this extra card without activating its power or changing the color.',
        insight_give_choice: 'Give this card to {name} without activating its power.',
        inspect_wait: 'You can inspect now; play when your turn arrives.',
        inspect_mismatch: 'Not playable now: match {color} or the discard character.',
        inspect_penalty: 'A draw of {n} is pending. This card cannot answer it.',
        inspect_legal: 'Playable now.', inspect_resolving: 'Finish the current decision first.',
        insight_normal: 'Shed this card. It has no additional effect.',
        insight_skip: '{name} misses their turn.',
        insight_reverse: 'Reverse direction; {previous} plays next.',
        insight_draw2: 'The penalty becomes {n} for {name}, who may counter it.',
        insight_counterAttack: 'Reverse direction. The penalty becomes {n} for {previous}, who may counter it.',
        insight_draw4Wild: 'Choose a color. The penalty becomes {n} for {name}, who may counter it.',
        insight_meh: 'Choose a color. The penalty becomes {n} for {name}, who may counter it.',
        insight_wild: 'Choose the color that play will continue with.',
        insight_sorry: 'You draw two cards, then play passes on.',
        insight_sorry_shield: 'Your current Phantom shield cancels your two-card draw and is consumed. Play then passes on.',
        insight_plato: 'Shed this card, but miss your next turn.',
        insight_chameleon: 'Choose an opponent and give them another card from your hand without activating it.',
        insight_nokhtha: 'Take another turn immediately after this card.',
        insight_hamour: 'Take up to four cards from underneath Hamour in the discard pile.',
        insight_bestOne: 'You choose: {name} discards two cards or draws two.',
        insight_dramaQueen: '{name} and {second} miss their turns.',
        insight_sugar: 'Disable superpowers until your next turn. Draws and counters keep their normal rules.',
        insight_umWajhain: 'Choose an opponent, then decide: they discard one card or draw one.',
        insight_boShlakh: 'Discard one extra card without activating it or changing the color.',
        insight_phantom: 'Cancel the pending penalty and shield yourself from your next draw.',
        insight_suppressed: 'Sugar has disabled this power. You shed the card without activating it.',
        insight_hamour_count: '{n} cards from the discard pile will join your hand.',
        insight_public_stack: 'The count depends on cards remaining beneath it in the discard pile (up to 4).',
        insight_self_cost: 'Caution: you take this penalty, not your opponent.',
        insight_skip_cost: 'The cost: you miss your next chance to play.',
        art_loading: 'Loading card…', art_retry: 'Retry image', art_unavailable: 'Original artwork could not load',
        state_sugar: 'Powers off until {name} plays', state_shield: 'Draw shield', state_last: 'Last card',
        decision_card_discard: 'Choose a card to discard — {card}',
        decision_card_give: 'Choose a card to give — {card}',
        decision_target: 'Choose a target — {card}', decision_color: 'Choose a color — {card}',
        decision_wait: '{name} is choosing', decision_count: '{name} · {n} cards',
        decision_finish_warning: 'Caution: this choice may empty {name}’s hand and let them win.',
        journal_penalty: '{name} drew {n} cards from the penalty',
        journal_draw_count: '{name} drew {n} cards',
        journal_powers_restored: 'Powers restored on {name}’s turn',
        journal_decision: '{name} chose: {choice}',
        journal_skipped: '{name} missed their turn', journal_effect: '{card}: {effect}',
        first_choice_tip: 'This is your decision; read the effect of each option before choosing.',
        decision_expired: 'The decision expired and play moved on. Check the current table state.',
        bot_style_racer: 'Racer', bot_style_guardian: 'Guardian', bot_style_tactician: 'Tactician',
        solo_menu: 'Pause', solo_paused: 'Game paused', solo_continue: 'Continue',
        solo_saved_description: 'Your round saves automatically on this device. Return to finish the same decision.',
        solo_save_failed: 'Saving is unavailable for this round. Keep this page open if you want to finish it.',
        solo_save_invalid: 'No valid saved round was found for this profile and version. You can start a new round.',
        solo_resume: 'Resume your saved round', solo_resume_title: 'Your previous round is still here',
        solo_resume_description: 'Resume it or replace it with a new round. Replacing it leaves the unfinished round without a result.',
        solo_save_exit: 'Save and leave', solo_exit: 'Leave', solo_stay: 'Stay in the round',
        solo_exit_title: 'Leave this round?', solo_replace: 'Replace the saved round with a new one',
        solo_finish_fact: '{name} emptied their hand first.', solo_wins: '{n} wins', solo_rounds: '{n} rounds in this session',
        solo_discard_moment: '{name} shed {card} with {source} without activating it.',
        practice_entry: 'Learn in 3 situations',
        practice_position: 'Practice {n}/3', practice_retry: 'Retry position', practice_next: 'Next position',
        practice_skip: 'Skip to a full match', practice_full_game: 'Start a full match',
        practice_goal_1: 'Inspect your cards. Play one matching the discard color or character; inspection never plays it.',
        practice_goal_2: 'You face +2. Inspect Counter Attack: it reverses direction and returns the penalty with two more cards.',
        practice_goal_3: 'Bo Shlakh discards an extra card without activating it. Try shedding Sorry and avoiding its two-card cost.',
        practice_success_1: 'You matched and played a card after inspecting it. In a full match you can inspect any card, even outside your turn.',
        practice_success_2: 'Direction reversed and +4 reached the attacker, who actually drew four cards. An opponent with a response could counter.',
        practice_success_3: 'You shed Bo Shlakh and Sorry, leaving one card without drawing two. This combination uses the original rules.',
        practice_alternative: 'Your choice followed the normal rules. Check the discard and card counts. Retry to explore the suggested combination, or continue.',
        practice_counter_cause: 'The attacker played Shush Shush: a two-card penalty.',
        telemetry_label: 'Record gameplay locally (optional)',
        telemetry_description: 'Records actions, decision types and control-wait intervals under a random identifier, without your name or hand contents. Stays on this device; never sent automatically. Turning it off clears the log. You can export and share it yourself.',
        telemetry_export: 'Download experience log JSON', telemetry_empty: 'Enable recording and try playing first.',
        practice_entry_description: 'Try matching, counters and a combination with the same rules. No results recorded.',
        practice_no_rewards: 'A training position with arranged hands; the same rules, with no results or Tamashi.',
    });
}
